-- RQ-006 surface 3: a story in an edition can be flagged to send its Link Take
-- instead of its one-sentence summary.
--
-- Generated by `prisma migrate diff --from-config-datasource --to-schema`, which
-- reported this single statement and no other drift, so applying it by hand does
-- exactly what `db push` would have done and nothing more. That check matters on a
-- database shared with production: a sync that turned out to want a DROP would have
-- been discovered after the fact.
--
-- Backward compatible with the code running in production at the time it is applied,
-- which never names this column. So the safe order is: apply this, confirm it, then
-- merge. The reverse breaks the dashboard and every edition save, because
-- `lib/editions/proposal.ts` and the edition PATCH route name the column explicitly.
--
-- IF NOT EXISTS so a second run is a no-op rather than an error.

ALTER TABLE "EditionArticle"
  ADD COLUMN IF NOT EXISTS "useLinkTake" BOOLEAN NOT NULL DEFAULT false;
