import crypto from "crypto";
import { config } from "@/lib/config";

/**
 * HMAC-signed unsubscribe tokens.
 *
 * Unsubscribe links previously embedded the raw subscriber ID, which made
 * them enumerable and let anyone unsubscribe arbitrary subscribers. Tokens
 * are now `base64url(subscriberId).hmacSha256(subscriberId)` so only links
 * generated by the server are accepted.
 */

function getSecret(): string {
  const secret = process.env.UNSUBSCRIBE_SECRET || process.env.CRON_SECRET;
  if (!secret) {
    throw new Error(
      "UNSUBSCRIBE_SECRET (or CRON_SECRET) must be set to sign unsubscribe links"
    );
  }
  return secret;
}

function sign(subscriberId: string): string {
  return crypto
    .createHmac("sha256", getSecret())
    .update(subscriberId)
    .digest("base64url");
}

export function generateUnsubscribeToken(subscriberId: string): string {
  const payload = Buffer.from(subscriberId, "utf8").toString("base64url");
  return `${payload}.${sign(subscriberId)}`;
}

/**
 * Verify a token and return the subscriber ID it was issued for,
 * or null if the token is malformed or the signature doesn't match.
 */
export function verifyUnsubscribeToken(token: string): string | null {
  const parts = token.split(".");
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    return null;
  }

  const subscriberId = Buffer.from(parts[0], "base64url").toString("utf8");
  if (!subscriberId) {
    return null;
  }

  const expected = Buffer.from(sign(subscriberId), "utf8");
  const provided = Buffer.from(parts[1], "utf8");

  if (
    expected.length !== provided.length ||
    !crypto.timingSafeEqual(expected, provided)
  ) {
    return null;
  }

  return subscriberId;
}

/**
 * Build the unsubscribe URL for a subscriber. Without a subscriber ID
 * (e.g. test sends), returns the generic unsubscribe page.
 */
export function buildUnsubscribeUrl(subscriberId?: string): string {
  const baseUrl = config.app.url;
  if (subscriberId) {
    return `${baseUrl}/unsubscribe?token=${generateUnsubscribeToken(subscriberId)}`;
  }
  return `${baseUrl}/unsubscribe`;
}
