import crypto from "crypto";
import { config } from "@/lib/config";

/**
 * HMAC-signed, purpose-scoped subscriber tokens.
 *
 * Unsubscribe links previously embedded the raw subscriber ID, which made
 * them enumerable and let anyone unsubscribe arbitrary subscribers. Tokens
 * are `base64url(subscriberId).hmacSha256(signingInput)` so only links
 * generated by the server are accepted.
 *
 * The purpose is part of what gets signed for everything except unsubscribe. Without that, one
 * token would open every subscriber-scoped surface: an unsubscribe link forwarded to a
 * colleague would open the sender's archive, and an archive link would unsubscribe whoever
 * clicked it.
 */

function getSecret(): string {
  const secret = process.env.UNSUBSCRIBE_SECRET || process.env.CRON_SECRET;
  if (!secret) {
    throw new Error(
      "UNSUBSCRIBE_SECRET (or CRON_SECRET) must be set to sign unsubscribe links"
    );
  }
  return secret;
}

export type TokenPurpose = "unsubscribe" | "archive";

/**
 * What actually gets signed, per purpose.
 *
 * `unsubscribe` signs the bare subscriber id and always will: tokens of that shape are in every
 * email already delivered, and breaking them would break the unsubscribe link in mail that has
 * already left. Every other purpose is prefixed, so a token minted for one cannot be replayed
 * against another.
 */
function signingInput(purpose: TokenPurpose, subscriberId: string): string {
  return purpose === "unsubscribe" ? subscriberId : `${purpose}:${subscriberId}`;
}

function sign(purpose: TokenPurpose, subscriberId: string): string {
  return crypto
    .createHmac("sha256", getSecret())
    .update(signingInput(purpose, subscriberId))
    .digest("base64url");
}

export function generateToken(purpose: TokenPurpose, subscriberId: string): string {
  const payload = Buffer.from(subscriberId, "utf8").toString("base64url");
  return `${payload}.${sign(purpose, subscriberId)}`;
}

/**
 * Verify a token for one purpose and return the subscriber ID it was issued for,
 * or null if the token is malformed, or signed for another purpose, or tampered with.
 */
export function verifyToken(purpose: TokenPurpose, token: string): string | null {
  const parts = token.split(".");
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    return null;
  }

  const subscriberId = Buffer.from(parts[0], "base64url").toString("utf8");
  if (!subscriberId) {
    return null;
  }

  const expected = Buffer.from(sign(purpose, subscriberId), "utf8");
  const provided = Buffer.from(parts[1], "utf8");

  if (
    expected.length !== provided.length ||
    !crypto.timingSafeEqual(expected, provided)
  ) {
    return null;
  }

  return subscriberId;
}

export function generateUnsubscribeToken(subscriberId: string): string {
  return generateToken("unsubscribe", subscriberId);
}

export function verifyUnsubscribeToken(token: string): string | null {
  return verifyToken("unsubscribe", token);
}

/**
 * Build the unsubscribe URL for a subscriber. Without a subscriber ID
 * (e.g. test sends), returns the generic unsubscribe page.
 */
export function buildUnsubscribeUrl(subscriberId?: string): string {
  const baseUrl = config.app.url;
  if (subscriberId) {
    return `${baseUrl}/unsubscribe?token=${generateUnsubscribeToken(subscriberId)}`;
  }
  return `${baseUrl}/unsubscribe`;
}
